prometheus:
  base-url: http://localhost:9090
  query: sum(kafka_consumergroup_lag{topic="my-topic",consumergroup="my-group"})
alertmanager:
  webhook-url: http://localhost:9093/api/v1/alerts
anomaly:
  multiplier: 2.0
ai:
  enabled: false
  openai-api-key: ${OPENAI_API_KEY:}
  model: gpt-4o
